package cjbind_ffi

public const foo: _cjbind_ty_1 = 4
public const bar: _cjbind_ty_1 = 8

public type _cjbind_ty_1 = UInt32

public type EasyToOverflow_EasyToOverflow = UInt64

public const k_k: EasyToOverflow_EasyToOverflow = 2147483648
public const k_expr_k_expr: EasyToOverflow_EasyToOverflow = 1152921504606846976
public const wow_wow: EasyToOverflow_EasyToOverflow = 2147483648
public const BAZ_BAZ: Int64 = 24
public const fuzz_fuzz: Float64 = 51.000000
public const BAZZ_BAZZ: UInt8 = 53
public const WAT_WAT: UInt8 = 0

// String value: Foo
public const bytestring_bytestring: VArray<UInt8, $4> = [70, 111, 111, 0]

// String value: <non-UTF-8>
public const NOT_UTF8_NOT_UTF8: VArray<UInt8, $5> = [240, 40, 140, 40, 0]
public const max_ull_max_ull: UInt64 = 18446744073709551615
