package cjbind_ffi

public const FOO_FOO: Int64 = 1
public const BAR_BAR: Int64 = 4
public const BAZ_BAZ: Int64 = 5
public const MIN_MIN: Int64 = -2147483648
public const BARR_BARR: Int64 = 1
public const BAZZ_BAZZ: Int64 = 7
public const I_RAN_OUT_OF_DUMB_NAMES_I_RAN_OUT_OF_DUMB_NAMES: Int64 = 7
public const HAZ_A_COMMENT_HAZ_A_COMMENT: Int64 = 1
public const HAZ_A_COMMENT_INSIDE_HAZ_A_COMMENT_INSIDE: Int64 = 2
