name: Sync Releases

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (optional, uses latest if not specified)'
        required: false
        type: string

permissions:
  contents: "write"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          python-version: "3.14"
          cache-dependency-glob: "**/*.py.lock"

      - name: Enable TCP BBR
        uses: Zxilly/actions-bbr@c3a8ea7012db3c0f4d5fcf6dd257c28f4cba9ead # v1.0.1

      - name: Download and sync releases
        run: uv run scripts/sync.py ${{ inputs.version || 'latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}
